### ISSUE TITLE
Does training complete its processing from the last point ? 

### ISSUE THREAD

**Issue by SamMohel** [whai362/PVT#17]
excuse me, Does training complete its processing from the last epoch if the machine is shut down suddenly or will start from the beginning

**Comment by whai362** [comment]
No, you can use dist_resume.sh.

**Comment by SamMohel** [comment]
> No, you can use dist_resume.sh.

i tried to use it but got 
`Creating model: 1
Traceback (most recent call last):
  File "main.py", line 442, in <module>
    main(args)
  File "main.py", line 251, in main
    drop_block_rate=None,
  File "/home/user/anaconda3/lib/python3.7/site-packages/timm/models/factory.py", line 59, in create_model
    raise RuntimeError('Unknown model (%s)' % model_name)
RuntimeError: Unknown model (1)
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/anaconda3/bin/python', '-u', 'main.py', '--model', '1', '--batch-size', '64', '--epochs', '300', '--data-path', '/media/user/use/PVT-main/images', '--output_dir', '/media/user/use/PVT-main/images', '--resume', '/media/user/use/PVT-main/images/checkpoint.pth', '--output_dir', '/media/user/use/PVT-main/output', '--resume', '/media/user/use/PVT-main/detection/work_dirs/retinanet_pvt_s_fpn_1x_coco_640/epoch_3.pth']' returned non-zero exit status 1.`
